### ISSUE TITLE
Transfer large size file on SDcard, WIIUFTPSERVER disconnect?

### ISSUE THREAD

**Issue by nhldp** [Laf111/WiiUFtpServer#14] opened 2022-03-05 03:10 UTC
When I tranfsfer some wup file to SD:\install folder, most files transfer finished, but a large size file: a more than 650M file, ftp client will disconnect with ftp server, file transfer failed.  And can not connect the ftp server again.
Once happened,  the list of files after large size file will transfer failed too.

After I pressed all key of gamepad, and wait some minutes, I can re-connect the ftp again.

**Comment by nhldp** [comment] 2022-03-05 03:27
I am using v9 version.
I tried more than 3 times, but the same.

I transfer this file finished when I change to use FTPiiU.

**Comment by Laf111** [comment] 2022-03-06 04:27
Hi, 

I'll have look to see ft i can reproduce and fix it but transfers to SDCard are not recommended because of the poor performance...
You should copy your WUP packages to your SDCard on your PC.

EDIT : are you transferring more than one file simultaneously ? iif it is the case, could you please try with only one transfer at the time ???

**Comment by Laf111** [comment] 2022-03-15 11:51
Should be fixed in V9-1

**Closed as completed by Laf111** 2022-03-15 11:51 UTC
