### ISSUE TITLE
File Corruption when using Filezilla on Windows, extra folders created by Cyberduck

### ISSUE THREAD

**Issue by grockk** [Laf111/WiiUFtpServer#10] opened 2022-02-02 22:55 UTC
Thanks for all you do! This is great as the other FTPiiU versions don't seem to work on tiramisu. I'm running WiiUFTPServer 8.1.

For Filezilla on Windows, if I send a file to the server and then download it right back I am getting a different CRC hash. It doesn't appear that the file didn't work (i was hacking BOTW) but each time i upload and download a file back I get a different CRC. I upload a known good file, the corrupted file i download back has same CRC each time but different than original.

I switched to using cyberduck which transfers correctly but for any generic "File_name.ext" i send, it is adding an extra folder to the Wii U called "File_name.extFile_name.ext". 

I can split these issues if you think they are unrelated.

**Comment by Laf111** [comment] 2022-02-03 08:21
Which version of FilleZilla is concerned ? (last one ?)
If when transfering the same files, the corruption appears only with filleZilla then it could/should be a FilleZillla issue.

I'll have a look to the other issue (cyberduck support)

**Comment by grockk** [comment] 2022-02-03 13:37
Filezilla 3.57. Is there a recommended FTP client or maybe its an encoding or settings that need to be set for specific features of the WiiUFTPServer. Thanks!

**Comment by Laf111** [comment] 2022-02-04 06:48
Well, not that i know of.

I use FilleZilla and WinScp. 
I've got a preference for FilleZilla but WinScp is powerful because scriptable.

No specific settings unless those recommended : 

- 90 sec for timeout which ensure to not timeout on transfer when a connection was started but paused and when a file greater than 100MB is in transfer and monopolizing the bandwith 
- 99 or unlimited retry number
- 0 sec between retries

The others default settings should be fine : 
- Auto ASCII/bin
- auto / IPV4 / V6
- allow retry in active mode (full active mode is not working)

Is your corruption issue is always reproductible ?
Would you mind please try this [RC version](https://1drv.ms/u/s!Apr2zdKB1g7fhEm1EF6okgNRldSO?e=bsxn3H) ?

Thanks in advance.
Have a nice day

**Comment by grockk** [comment] 2022-02-04 15:08
Yes. Always reproducible. I get the exact same change in checksum when I send a file on a round trip back and forth to the Wii U. 

I didn't realize Filezilla runs on Mac too so i tried it last night but I got the exact same checksum change when using mac version as windows version. So maybe it is Filezilla or at least they are both interacting with the wii u server the same way. 

I'll try the RC version later tonight.

Oh and I am running tiramisu and launching HBL from the mii maker channel.

**Comment by grockk** [comment] 2022-02-04 22:24
RC version halfway fixed the issue. 

Transfers over FTP to the SD card now make the round trip with correct checksum.  But it is very slow to upload. about 0.25 mb/s vs 3 mb/s to download back. 

But to the USB, small files are ok but large file sometimes gets corrupted. Speeds are always good but occasionally i got corruption. The change in checksum is different each time now. not sure if thats a clue.

I've been using U-king.rpx from BOTW as my large test file (and where i first noticed the issue) and a zipped random text file as my small file. I was using the tmp folder on the USB and root of SD card.

**Comment by Laf111** [comment] 2022-02-08 15:01
Sorry for my late response, i'm quite busy those days...

Well, i've done more checks than the usual ones i do before releasing a version and it is quite difficult to get a "small context" where the bug occurs each time.

To check the CRC validity, i usually use a Wind Waker Save and i also check that the rights were correctly set.
Then i DL/UL the whole game Fast Racing Neo.

When i compare the 9000 files transferred for Fast Racing Neo, only 3 of them are corrupted.
When i try the isolate less files, the corruption disappear on this files (too)...

So i have to check further what's going on.

**Comment by grockk** [comment] 2022-02-08 18:25
How strange. Yes. Exactly. I'm pleased you could reproduce but sorry that it just means more work! Thank you for your effort. unfortunately I will be away from my Wii U until mid-march so I won't be able to test until then.

**Comment by Laf111** [comment] 2022-02-09 03:55
If you have the time, please do you mind check this [one ](https://1drv.ms/u/s!Apr2zdKB1g7fhEoouH8usBj3P_Tr?e=dRWiqa)? 
It fixes corruption's files on my side.
Thanks in advance.

**Comment by Laf111** [comment] 2022-02-15 15:44
Hey, 

I have a question : what is your setup ? 
Do you use the builtin WIFI or an ethernet plug to connect the WIIU on your NAS ? 
Then how your PC is connected to your NAS ?

I use an ethernet adapter (UGreen one) on my WiiU. I get file's corruption (still about 3 files on 9000) ONLY when my PC is connected with Wifi to my NAS. 

When i use an ethernet cable or via powerline  i've got no files corrupted.

![image](https://user-images.githubusercontent.com/47532310/154137025-39b82328-3cbb-4c17-b42b-585f460270e4.png)

**Comment by grockk** [comment] 2022-02-15 22:46
I’m away until March 15. But for setup, Wii U is connected with official Wii Ethernet adapter and Mac and Pc are both on Ethernet. I haven’t tested new build since my last update.

**Comment by Laf111** [comment] 2022-02-16 13:48
**When using WIFI for connecting the WiiU and the PC :** downgrading to the 802.11g WIFI protocol on my NAS fix the corruption on files uploaded. I was running on 802.11n as many users nowdays i suppose.

802.11n specifications came out from 2007 to 2012 while the WiiU was built. 
I suppose that it might explain some things...

**Comment by Laf111** [comment] 2022-02-17 14:18
To be honest, i'm not an expert of network (it is my first work on network sockets...) 

It seems that "theoretically" you should have no CRC errors but in reality a simple faulty ethernet cable could cause CRC errors (also even just an instantaneous network loss). 
Network experts talk about issue when over than 1% of CRC errors are raised.

So it seems that there's no warranty that files uploaded are healthy unless adding a CRC check on both sides.

**This might explain some misadventures happened to some people who bricked their console after uploading system's files with checking only their sizes (which are equals even on a CRC failure) !**

I plan to implement the XCRC ftp command on the server :

_The XCRC hash command asks the server to perform a cyclic redundancy check using the CRC-32 algorithm on the 
specified file. If the XCRC command is supported, the server will respond with the result of the calculation. 
FTP clients can use this command to verify that the file was transferred without corruption by comparing the 
server's response with its own calculation._

And recommend a FTP client that support this feature, such as Smart_FTP (unfortunately FilleZilla doesn't...)

**Comment by grockk** [comment] 2022-02-18 03:49
There definitely seems like some bricks are file corruption during FTP transfer. CRC verification will be a valuable feature even at the cost of speed gains you've demonstrated. Thanks for keeping at this.

**Comment by Laf111** [comment] 2022-02-21 18:20
When you'll have the time, please try to reproduce your issue with the V8-2 : https://github.com/Laf111/WiiUFtpServer/releases/tag/V8-2

**Comment by Laf111** [comment] 2022-02-28 13:50
Hi, 

I have no error now even in Wifi.
I close the issue, if needed we will re-open it.

**Closed as completed by Laf111** 2022-02-28 13:50 UTC
